int32 boom_angle_sensor_angle

int32 wind_sensor_0_speed
int32 wind_sensor_0_direction
int32 wind_sensor_0_reference
int32 wind_sensor_1_speed
int32 wind_sensor_1_direction
int32 wind_sensor_1_reference
int32 wind_sensor_2_speed
int32 wind_sensor_2_direction
int32 wind_sensor_2_reference

string   gps_can_timestamp
float64  gps_can_latitude
float64  gps_can_longitude
bool     gps_can_latitude_loc
bool     gps_can_longitude_loc
int32    gps_can_groundspeed
int32    gps_can_track_made_good
int32    gps_can_true_heading
int32    gps_can_magnetic_variation
bool     gps_can_magnetic_variation_sense

string   gps_ais_timestamp
float64  gps_ais_latitude
float64  gps_ais_longitude
bool     gps_ais_latitude_loc
bool     gps_ais_longitude_loc
int32    gps_ais_groundspeed
int32    gps_ais_track_made_good
int32    gps_ais_true_heading
int32    gps_ais_magnetic_variation
bool     gps_ais_magnetic_variation_sense

int32 accelerometer_x_axis_acceleration
int32 accelerometer_y_axis_acceleration
int32 accelerometer_z_axis_acceleration
