int32 boom_angle_sensor_angle

int32 wind_sensor_0_speed
int32 wind_sensor_0_direction
int32 wind_sensor_0_reference
int32 wind_sensor_1_speed
int32 wind_sensor_1_direction
int32 wind_sensor_1_reference
int32 wind_sensor_2_speed
int32 wind_sensor_2_direction
int32 wind_sensor_2_reference

string   gps_timestamp
float64  gps_latitude
float64  gps_longitude
bool     gps_latitude_loc
bool     gps_longitude_loc
int32    gps_groundspeed
int32    gps_track_made_good
int32    gps_true_heading
int32    gps_magnetic_variation
bool     gps_magnetic_variation_sense

int32 accelerometer_x_axis_acceleration
int32 accelerometer_y_axis_acceleration
int32 accelerometer_z_axis_acceleration
